version: '3'

services:
  
  rabbitmq:
    hostname: rabbitmq
    image: 'rabbitmq:3.6-management-alpine'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '5672:5672'
      - '15672:15672'

  worker:
    build: 
    context: worker
    volumes:
      - ./worker:/app
      - shared_images:/images
    user: nobody
    environment:
      - PYTHONUNBUFFERED=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    depends_on:
      - rabbitmq
      - server

  server:
    container_name: server
    image: server:0.0.5
    build: 
      context: server
    ports:
      - "3001:3001"
    environment:
    - EXTERNAL_PORT=3001
    - PGDATABASE=pgdb
    - PGUSER=pguser
    - PGPASSWORD=pguser
    - PGHOST=postgres
    - CREDITS=5000
    - SECRET_KEY=califragilisticospiralitoso
    - RABBITMQ_PORT=5672
    - UPLOAD_PATH=/images
    volumes:
      - shared_images:/images
    #build: server
    #volumes:
    #  - ./server:/app
    #ports:
    #  - 8000:5000
    #environment:
    #  - LC_ALL=C.UTF-8
    #  - LANG=C.UTF-8
    #depends_on:
    #  - rabbitmq

  postgres:
    container_name: postgres
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_DB=pgdb
    volumes:
      - nps_data:/var/lib/postgresql/data

  producer:
    container_name: producer
    ports:
      - "3002:5000"
    depends_on:
    - rabbitmq
    build:
      context: producer
  



volumes:
  nps_data: {}
  shared_images: {}




