@startuml

actor User

participant Middleweres
participant Controllers
database Postgres

autonumber 
User -> Middleweres ++: GET/datasets/
group step: Authentication
    Middleweres -> Middleweres : CheckAuth 
else Token Not Provided
    autonumber 3
    Middleweres --[#red]> User : 401 Unauthorized - Token Not Provided
else Token Not Valid  
    autonumber 3
    Middleweres --[#red]> User : 401 Unauthorized - Token Not Valid
end

group step: GetMineDatasets   
    autonumber 3
    Middleweres -> Controllers ++: getAllMine
    Controllers -> Postgres ++: getAllByUseruid(userUID)
    Postgres --> Controllers : Datasets
    Controllers --> User : 200 OK
else token is not valid or not provided
    Postgres --[#red]> Controllers : 401 Unauthorized
    Controllers --[#red]> User : 401 Unauthorized
end

@enduml
