@startuml inferenceModel

actor User
participant Middlewares
participant Controllers
database Postgres
participant Producer
participant Worker

autonumber
User -> Middlewares ++: GET/models/inference/:id

group step: Authentication
    Middlewares -> Middlewares : CheckAuth
else Unauthorized
    autonumber 3
    Middlewares --[#red]> User : 401 Unauthorized - Token not provided
    autonumber 3
    Middlewares --[#red]> User : 401 Unauthorized - Token not valid
end

group step: Ownership
    autonumber 3
    Middlewares -> Middlewares : CheckOwner
else Unauthorized
    autonumber 4
    Middlewares --[#red]> User : 401 Unauthorized - You are not the owner of this model
else Not Found
    autonumber 4
    Middlewares --[#red]> User : 404 Not Found - Model not found
end

group step: UpdateUser
    autonumber 4
    Middlewares -> Controllers --++: inference
    Controllers -> Postgres ++: findByPK
    Postgres --> Controllers: return Model
    Controllers -> Postgres : findByPK
    Postgres --> Controllers: return Dataset
    Controllers -> Producer ++: startJob
    Producer -> Worker ++: longtime_add
    Worker -> Worker : inference
    Worker --> Producer : jobId
    Producer -> Controllers : jobId
    Controllers --[#green]> User : 200 OK - jobId
else Inference Failed
    autonumber 8
    Postgres --[#red]> Controllers : 500 Internal Server Error
    Controllers --[#red]> User : 500 Internal Server Error
    autonumber 12
    Worker --[#red]> Producer --: 500 Internal Server Error
    Producer --[#red]> Controllers : 500 Internal Server Error
    Controllers --[#red]> User : 500 Internal Server Error
    autonumber 13
    Producer --[#red]> Controllers --: 500 Internal Server Error
    Controllers --[#red]> User : 500 Internal Server Error
else Not Found
    autonumber 6
    Postgres --[#red]> Controllers : 404 Not Found - Model not found
    Controllers --[#red]> User : 404 Not Found - Model not found
    autonumber 8
    Postgres --[#red]> Controllers --: 404 Not Found - Dataset not found
    Controllers --[#red]> User --: 404 Not Found - Dataset not found
end

@enduml