@startuml GetMineModels

actor User

participant Middlewares
participant Controllers
database Postgres

autonumber 
User -> Middlewares ++: GET/models/
group step: Authentication
    Middlewares -> Middlewares : CheckAuth
else Auth Failed
    autonumber 3
    Middlewares --[#red]> User : 401 Unauthorized - Token not provided
    autonumber 3
    Middlewares --[#red]> User : 401 Unauthorized - Token not valid
end

group step: Get Mine Models   
    autonumber 3
    Middlewares -> Controllers --++: getAllMine
    Controllers -> Postgres ++: findAll
    Postgres --> Controllers : return Models
    Controllers --[#green]> User : 200 OK - Models
else Internal Server Error
    autonumber 5
    Postgres --[#red]> Controllers --: 500 Internal Server Error
    Controllers --[#red]> User --: 500 Internal Server Error
end

@enduml
